import { PickupPoint } from '../types';

export const pickupCatalog: PickupPoint[] = [
  { id: 'pickup-wipro-gate', name: 'Wipro Gate', stationId: 'station-ecity', stationName: 'Electronic City', latitude: 12.8467, longitude: 77.6624 },
  { id: 'pickup-infosys-gate', name: 'Infosys Gate', stationId: 'station-ecity', stationName: 'Electronic City', latitude: 12.8459, longitude: 77.6666 },
  { id: 'pickup-velankani', name: 'Velankani Tech Park', stationId: 'station-ecity', stationName: 'Electronic City', latitude: 12.8449, longitude: 77.6615 },
  { id: 'pickup-neeladri', name: 'Neeladri Road', stationId: 'station-ecity', stationName: 'Electronic City', latitude: 12.8442, longitude: 77.6574 },
  { id: 'pickup-doddathogur', name: 'Doddathogur Cross', stationId: 'station-ecity', stationName: 'Electronic City', latitude: 12.8365, longitude: 77.6642 },
  { id: 'pickup-singasandra', name: 'Singasandra', stationId: 'station-ecity', stationName: 'Electronic City', latitude: 12.884, longitude: 77.654 },
  { id: 'pickup-kudlu-gate', name: 'Kudlu Gate', stationId: 'station-hsr', stationName: 'HSR Layout', latitude: 12.8936, longitude: 77.6513 },
  { id: 'pickup-hosa-road', name: 'Hosa Road Junction', stationId: 'station-konappana', stationName: 'Konappana Agrahara', latitude: 12.8721, longitude: 77.6647 },
  { id: 'pickup-konappana', name: 'Konappana Bus Stop', stationId: 'station-konappana', stationName: 'Konappana Agrahara', latitude: 12.8513, longitude: 77.6541 },
  { id: 'pickup-siemens', name: 'Siemens Campus', stationId: 'station-konappana', stationName: 'Konappana Agrahara', latitude: 12.8553, longitude: 77.6515 },
  { id: 'pickup-pes-it', name: 'PES IT Junction', stationId: 'station-konappana', stationName: 'Konappana Agrahara', latitude: 12.8581, longitude: 77.6493 },
  { id: 'pickup-huskur', name: 'Huskur Junction', stationId: 'station-huskur', stationName: 'Huskur Road', latitude: 12.8188, longitude: 77.6924 },
  { id: 'pickup-dmart', name: 'D Mart Huskur', stationId: 'station-huskur', stationName: 'Huskur Road', latitude: 12.817, longitude: 77.6972 },
  { id: 'pickup-ecity-phase2', name: 'Electronic City Phase 2', stationId: 'station-huskur', stationName: 'Huskur Road', latitude: 12.8149, longitude: 77.6968 },
  { id: 'pickup-bommasandra', name: 'Bommasandra Industrial', stationId: 'station-bommasandra', stationName: 'Bommasandra', latitude: 12.8019, longitude: 77.7018 },
  { id: 'pickup-narayana', name: 'Narayana Health City', stationId: 'station-bommasandra', stationName: 'Bommasandra', latitude: 12.8008, longitude: 77.6846 },
  { id: 'pickup-chandapura', name: 'Chandapura Circle', stationId: 'station-bommasandra', stationName: 'Bommasandra', latitude: 12.8011, longitude: 77.7039 },
  { id: 'pickup-attibele', name: 'Attibele Checkpost', stationId: 'station-bommasandra', stationName: 'Bommasandra', latitude: 12.7842, longitude: 77.7721 },
  { id: 'pickup-silkboard', name: 'Silk Board Flyover', stationId: 'station-silkboard', stationName: 'Central Silk Board', latitude: 12.916, longitude: 77.6239 },
  { id: 'pickup-madiwala', name: 'Madiwala Police Station', stationId: 'station-silkboard', stationName: 'Central Silk Board', latitude: 12.9188, longitude: 77.6176 },
  { id: 'pickup-hsr-27th', name: 'HSR 27th Main', stationId: 'station-hsr', stationName: 'HSR Layout', latitude: 12.9082, longitude: 77.6475 },
  { id: 'pickup-hsr-bda', name: 'HSR BDA Complex', stationId: 'station-hsr', stationName: 'HSR Layout', latitude: 12.9129, longitude: 77.6382 },
  { id: 'pickup-agara', name: 'Agara Lake', stationId: 'station-hsr', stationName: 'HSR Layout', latitude: 12.9215, longitude: 77.651 },
  { id: 'pickup-btm2', name: 'BTM 2nd Stage', stationId: 'station-btm', stationName: 'BTM Layout', latitude: 12.9169, longitude: 77.6105 },
  { id: 'pickup-jayadeva', name: 'Jayadeva Hospital', stationId: 'station-btm', stationName: 'BTM Layout', latitude: 12.9189, longitude: 77.5956 },
  { id: 'pickup-forum', name: 'Forum Mall', stationId: 'station-koramangala', stationName: 'Koramangala', latitude: 12.9349, longitude: 77.6113 },
  { id: 'pickup-sonyworld', name: 'Sony World Junction', stationId: 'station-koramangala', stationName: 'Koramangala', latitude: 12.9353, longitude: 77.6393 },
  { id: 'pickup-ejipura', name: 'Ejipura Signal', stationId: 'station-koramangala', stationName: 'Koramangala', latitude: 12.9304, longitude: 77.626 },
  { id: 'pickup-bellandur-gate', name: 'Bellandur Gate', stationId: 'station-bellandur', stationName: 'Bellandur', latitude: 12.9378, longitude: 77.679 },
  { id: 'pickup-iblur', name: 'Iblur Junction', stationId: 'station-bellandur', stationName: 'Bellandur', latitude: 12.9248, longitude: 77.6773 },
  { id: 'pickup-haralur', name: 'Haralur Road', stationId: 'station-hsr', stationName: 'HSR Layout', latitude: 12.9004, longitude: 77.6492 },
];
